version: '3.8'

services:
  # JSON Server for mock API
  json-server:
    image: node:18-alpine
    container_name: financial-app-json-server
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
      - ./headers.js:/app/headers.js
    ports:
      - "4000:4000"
    command: >
      sh -c "npm install -g json-server &&
             json-server --watch db.json --port 4000 ./headers.js"
    networks:
      - financial-app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/transactions"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Next.js Application
  financial-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: financial-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - JSON_SERVER_HOST=http://json-server:4000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      json-server:
        condition: service_healthy
    command: npm run dev
    networks:
      - financial-app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  financial-app-network:
    driver: bridge 