apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: financial-app
data:
  db.json: |
    {
      "transactions": [
        {
          "id": "txn_001",
          "amount": 100.5,
          "currency": "USD",
          "status": "completed",
          "timestamp": "2025-06-01T12:00:00Z",
          "description": "Payment for groceries",
          "merchant": {
            "name": "GroceryMart",
            "id": "mcht_001"
          },
          "payment_method": {
            "type": "credit_card",
            "last4": "1234",
            "brand": "visa"
          },
          "sender": {
            "name": "Alice",
            "account_id": "acc_001"
          },
          "receiver": {
            "name": "GroceryMart",
            "account_id": "acc_101"
          },
          "fees": {
            "processing_fee": 2.5,
            "currency": "USD"
          },
          "metadata": {
            "order_id": "ord_001",
            "customer_id": "cust_001"
          }
        }
      ]
    } 