apiVersion: v1
kind: ConfigMap
metadata:
  name: headers-config
  namespace: financial-app
data:
  headers.js: |
    module.exports = (req, res, next) => {
      res.header('Access-Control-Allow-Origin', '*');
      res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
      next();
    }; 